# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://donedealdesigns.com
title: Done Deal Designs
email: support@bluefenix.net
author: Brian Dailey
description: > # "Write an awesome description for your new site here. 
  Outdoor Designs
copyright: 'Copyright &copy; 2020 Brian Dailey. All Rights Reserved.'
credits: 'Maintained by <a href="https://bluefenix.net">Blue Fenix Productions</a>'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://facebook.com/donedealdesigns/
  - title: phone
    url: tel:1-281-300-2961
  - title: email
    url: mailto:info@donedealdesigns.com
    