# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://donedealdesigns.com
title: Done Deal Designs
email: support@bluefenix.net
author: Brian Dailey
description: > # "Write an awesome description for your new site here. 
  Done Deal Designs, LLC specializes in outdoor design and construction including pools, spas, landscaping, hardscaping, lighting, outdoor kitchens, outdoor living areas, putting greens and so much more.  Our team provides turnkey service by working with you throughout the entire process to bring your vision for your outdoor space to life.  If you aren't quite sure what you can do to optimize your outdoor space we are happy to create some options for you!  
copyright: 'Copyright &copy; 2021 Brian Dailey. All Rights Reserved.'
credits: 'Maintained by <a href="https://bluefenix.net"><img src="https://bluefenix.net/favicon.png" width="20"/> Blue Fenix Productions</a>'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://facebook.com/donedealdesigns/
  - title: phone
    url: tel:1-281-300-2961
  - title: inbox 
    url: mailto:info@donedealdesigns.com
    